### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by louis77** [kousu/radiobrowser-server#7]
Before we start to push work to public Git repos we should think a bit about the licenses we choose for our work.

radio-browser.info has the following licensing terms stated on their web site:
> Data license: public domain, software license: GPL, server software: open source

**Data**
Since the data is not in any Git repo right now and there is no specific license, I propose to use the CC0 license which is the recommended public-domain license for non-software work by the FSF:
https://www.gnu.org/licenses/license-list.html#CC0

**radiobrowser-api-rust**
Using AGPL 3.0 license: https://github.com/segler-alex/radiobrowser-api-rust. So we obviously have to use that license unchanged. AGPL is GPL plus: 
> if you run a modified program on a server and let other users communicate with it there, your server must also allow them to download the source code corresponding to the modified version running there.

**New works**
For any new scripts we produce we could use the GPL3 license, for any other software that runs on a server AGPL3.

Let me know if you are fine with that or if you have any other thoughts or experience.

**Comment by kousu** [comment]
Those are fine plans. I agree. Let's go with them.
